export const ATTRIBUTES = {
  CHARACTER: "CHARACTER",
  COMPANY: "company",
  SERIES: "series",
  INITIAL_RELEASE: "initial_release_year",
  GENDER: "gender",
  RANGE_TYPE: "range_type",
};

export const ATTRIBUTE_LABELS = {
  [ATTRIBUTES.CHARACTER]: "Character",
  [ATTRIBUTES.COMPANY]: "Company",
  [ATTRIBUTES.SERIES]: "Series",
  [ATTRIBUTES.INITIAL_RELEASE]: "Release Year",
  [ATTRIBUTES.GENDER]: "Gender",
  [ATTRIBUTES.RANGE_TYPE]: "Range Type",
};

export const ATTRIBUTE_INDEX = {
  0: ATTRIBUTES.CHARACTER,
  1: ATTRIBUTES.COMPANY,
  2: ATTRIBUTES.SERIES,
  3: ATTRIBUTES.INITIAL_RELEASE,
  4: ATTRIBUTES.GENDER,
  5: ATTRIBUTES.RANGE_TYPE,
};
