export const CHARACTERS = [
  {
    "name": "Mario",
    "company": "Nintendo",
    "series": "Super Mario",
    "initial_release_year": "1981",
    "gender": "Male",
    "range_type": "Close-range",
    "image_url": "/Character-images/Mario.png",
  },
  {
    "name": "Donkey Kong",
    "company": "Nintendo",
    "series": "Donkey Kong",
    "initial_release_year": "1981",
    "gender": "Male",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Donkey_Kong.png",
  },
  {
    "name": "Link",
    "company": "Nintendo",
    "series": "The Legend of Zelda",
    "initial_release_year": "1986",
    "gender": "Male",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Link.png",
  },
  {
    "name": "Samus",
    "company": "Nintendo",
    "series": "Metroid",
    "initial_release_year": "1986",
    "gender": "Female",
    "range_type": "Long-range",
    "image_url": "/Character-images/Samus.png",
  },
  {
    "name": "Yoshi",
    "company": "Nintendo",
    "series": "Yoshi",
    "initial_release_year": "1990",
    "gender": "Male",
    "range_type": "Close-range",
    "image_url": "/Character-images/Yoshi.png",
  },
  {
    "name": "Kirby",
    "company": "Nintendo",
    "series": "Kirby",
    "initial_release_year": "1992",
    "gender": "Male",
    "range_type": "Close-range",
    "image_url": "/Character-images/Kirby.png",
  },
  {
    "name": "Fox",
    "company": "Nintendo",
    "series": "Star Fox",
    "initial_release_year": "1993",
    "gender": "Male",
    "range_type": "Long-range",
    "image_url": "/Character-images/Fox.png",
  },
  {
    "name": "Pikachu",
    "company": "Nintendo",
    "series": "Pok\u00e9mon",
    "initial_release_year": "1996",
    "gender": "Varies",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Pikachu.png",
  },
  {
    "name": "Luigi",
    "company": "Nintendo",
    "series": "Super Mario",
    "initial_release_year": "1983",
    "gender": "Male",
    "range_type": "Close-range",
    "image_url": "/Character-images/Luigi.png",
  },
  {
    "name": "Ness",
    "company": "Nintendo",
    "series": "EarthBound",
    "initial_release_year": "1994",
    "gender": "Male",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Ness.png",
  },
  {
    "name": "Captain Falcon",
    "company": "Nintendo",
    "series": "F-Zero",
    "initial_release_year": "1990",
    "gender": "Male",
    "range_type": "Close-range",
    "image_url": "/Character-images/Captain_Falcon.png",
  },
  {
    "name": "Jigglypuff",
    "company": "Nintendo",
    "series": "Pok\u00e9mon",
    "initial_release_year": "1996",
    "gender": "Varies",
    "range_type": "Close-range",
    "image_url": "/Character-images/Jigglypuff.png",
  },
  {
    "name": "Peach",
    "company": "Nintendo",
    "series": "Super Mario",
    "initial_release_year": "1985",
    "gender": "Female",
    "range_type": "Close-range",
    "image_url": "/Character-images/Peach.png",
  },
  {
    "name": "Daisy",
    "company": "Nintendo",
    "series": "Super Mario",
    "initial_release_year": "1989",
    "gender": "Female",
    "range_type": "Close-range",
    "image_url": "/Character-images/Daisy.png",
  },
  {
    "name": "Bowser",
    "company": "Nintendo",
    "series": "Super Mario",
    "initial_release_year": "1985",
    "gender": "Male",
    "range_type": "Close-range",
    "image_url": "/Character-images/Bowser.png",
  },
  {
    "name": "Ice Climbers",
    "company": "Nintendo",
    "series": "Ice Climber",
    "initial_release_year": "1985",
    "gender": "Varies",
    "range_type": "Close-range",
    "image_url": "/Character-images/Ice_Climbers.png",
  },
  {
    "name": "Sheik",
    "company": "Nintendo",
    "series": "The Legend of Zelda",
    "initial_release_year": "1998",
    "gender": "Female",
    "range_type": "Close-range",
    "image_url": "/Character-images/Sheik.png",
  },
  {
    "name": "Zelda",
    "company": "Nintendo",
    "series": "The Legend of Zelda",
    "initial_release_year": "1986",
    "gender": "Female",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Zelda.png",
  },
  {
    "name": "Dr. Mario",
    "company": "Nintendo",
    "series": "Dr. Mario",
    "initial_release_year": "1990",
    "gender": "Male",
    "range_type": "Close-range",
    "image_url": "/Character-images/Dr._Mario.png",
  },
  {
    "name": "Pichu",
    "company": "Nintendo",
    "series": "Pok\u00e9mon",
    "initial_release_year": "2000",
    "gender": "Varies",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Pichu.png",
  },
  {
    "name": "Falco",
    "company": "Nintendo",
    "series": "Star Fox",
    "initial_release_year": "1997",
    "gender": "Male",
    "range_type": "Long-range",
    "image_url": "/Character-images/Falco.png",
  },
  {
    "name": "Marth",
    "company": "Nintendo",
    "series": "Fire Emblem",
    "initial_release_year": "1990",
    "gender": "Male",
    "range_type": "Close-range",
    "image_url": "/Character-images/Marth.png",
  },
  {
    "name": "Lucina",
    "company": "Nintendo",
    "series": "Fire Emblem",
    "initial_release_year": "2012",
    "gender": "Female",
    "range_type": "Close-range",
    "image_url": "/Character-images/Lucina.png",
  },
  {
    "name": "Young Link",
    "company": "Nintendo",
    "series": "The Legend of Zelda",
    "initial_release_year": "2000",
    "gender": "Male",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Young_Link.png",
  },
  {
    "name": "Ganondorf",
    "company": "Nintendo",
    "series": "The Legend of Zelda",
    "initial_release_year": "1998",
    "gender": "Male",
    "range_type": "Close-range",
    "image_url": "/Character-images/Ganondorf.png",
  },
  {
    "name": "Mewtwo",
    "company": "Nintendo",
    "series": "Pok\u00e9mon",
    "initial_release_year": "1996",
    "gender": "Varies",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Mewtwo.png"
  },
  {
    "name": "Roy",
    "company": "Nintendo",
    "series": "Fire Emblem",
    "initial_release_year": "2002",
    "gender": "Male",
    "range_type": "Close-range",
    "image_url": "/Character-images/Roy.png"
  },
  {
    "name": "Chrom",
    "company": "Nintendo",
    "series": "Fire Emblem",
    "initial_release_year": "2012",
    "gender": "Male",
    "range_type": "Close-range",
    "image_url": "/Character-images/Chrom.png"
  },
  {
    "name": "Mr. Game & Watch",
    "company": "Nintendo",
    "series": "Game & Watch",
    "initial_release_year": "1980",
    "gender": "Varies",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Mr._Game_&_Watch.png"
  },
  {
    "name": "Meta Knight",
    "company": "Nintendo",
    "series": "Kirby",
    "initial_release_year": "1993",
    "gender": "Male",
    "range_type": "Close-range",
    "image_url": "/Character-images/Meta_Knight.png"
  },
  {
    "name": "Pit",
    "company": "Nintendo",
    "series": "Kid Icarus",
    "initial_release_year": "1986",
    "gender": "Male",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Pit.png"
  },
  {
    "name": "Dark Pit",
    "company": "Nintendo",
    "series": "Kid Icarus",
    "initial_release_year": "2012",
    "gender": "Male",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Dark_Pit.png"
  },
  {
    "name": "Zero Suit Samus",
    "company": "Nintendo",
    "series": "Metroid",
    "initial_release_year": "2004",
    "gender": "Female",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Zero_Suit_Samus.png"
  },
  {
    "name": "Wario",
    "company": "Nintendo",
    "series": "Wario",
    "initial_release_year": "1992",
    "gender": "Male",
    "range_type": "Close-range",
    "image_url": "/Character-images/Wario.png"
  },
  {
    "name": "Snake",
    "company": "Konami",
    "series": "Metal Gear",
    "initial_release_year": "1987",
    "gender": "Male",
    "range_type": "Long-range",
    "image_url": "/Character-images/Snake.png"
  },
  {
    "name": "Ike",
    "company": "Nintendo",
    "series": "Fire Emblem",
    "initial_release_year": "2005",
    "gender": "Male",
    "range_type": "Close-range",
    "image_url": "/Character-images/Ike.png"
  },
  {
    "name": "Pokemon Trainer",
    "company": "Nintendo",
    "series": "Pok\u00e9mon",
    "initial_release_year": "1996",
    "gender": "Varies",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Pokémon_Trainer.png"
  },
  {
    "name": "Diddy Kong",
    "company": "Nintendo",
    "series": "Donkey Kong",
    "initial_release_year": "1994",
    "gender": "Male",
    "range_type": "Close-range",
    "image_url": "/Character-images/Diddy_Kong.png"
  },
  {
    "name": "Lucas",
    "company": "Nintendo",
    "series": "Mother",
    "initial_release_year": "2006",
    "gender": "Male",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Lucas.png"
  },
  {
    "name": "Sonic",
    "company": "Sega",
    "series": "Sonic the Hedgehog",
    "initial_release_year": "1991",
    "gender": "Male",
    "range_type": "Close-range",
    "image_url": "/Character-images/Sonic.png"
  },
  {
    "name": "King Dedede",
    "company": "Nintendo",
    "series": "Kirby",
    "initial_release_year": "1992",
    "gender": "Male",
    "range_type": "Close-range",
    "image_url": "/Character-images/King_Dedede.png"
  },
  {
    "name": "Olimar",
    "company": "Nintendo",
    "series": "Pikmin",
    "initial_release_year": "2001",
    "gender": "Male",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Olimar.png"
  },
  {
    "name": "Lucario",
    "company": "Nintendo",
    "series": "Pok\u00e9mon",
    "initial_release_year": "2006",
    "gender": "Varies",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Lucario.png"
  },
  {
    "name": "R.O.B.",
    "company": "Nintendo",
    "series": "R.O.B.",
    "initial_release_year": "1985",
    "gender": "Varies",
    "range_type": "Mid-range",
    "image_url": "/Character-images/R.O.B..png"
  },
  {
    "name": "Toon Link",
    "company": "Nintendo",
    "series": "The Legend of Zelda",
    "initial_release_year": "2002",
    "gender": "Male",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Toon_Link.png"
  },
  {
    "name": "Wolf",
    "company": "Nintendo",
    "series": "Star Fox",
    "initial_release_year": "1997",
    "gender": "Male",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Wolf.png"
  },
  {
    "name": "Villager",
    "company": "Nintendo",
    "series": "Animal Crossing",
    "initial_release_year": "2001",
    "gender": "Varies",
    "range_type": "Close-range",
    "image_url": "/Character-images/Villager.png"
  },
  {
    "name": "Mega Man",
    "company": "Capcom",
    "series": "Mega Man",
    "initial_release_year": "1987",
    "gender": "Male",
    "range_type": "Long-range",
    "image_url": "/Character-images/Mega_Man.png"
  },
  {
    "name": "Wii Fit Trainer",
    "company": "Nintendo",
    "series": "Wii Fit",
    "initial_release_year": "2007",
    "gender": "Varies",
    "range_type": "Close-range",
    "image_url": "/Character-images/Wii_Fit_Trainer.png"
  },
  {
    "name": "Rosalina & Luma",
    "company": "Nintendo",
    "series": "Super Mario",
    "initial_release_year": "2007",
    "gender": "Female",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Rosalina.png"
  },
  {
    "name": "Little Mac",
    "company": "Nintendo",
    "series": "Punch-Out!!",
    "initial_release_year": "1983",
    "gender": "Male",
    "range_type": "Close-range",
    "image_url": "/Character-images/Little_Mac.png"
  },
  {
    "name": "Greninja",
    "company": "Nintendo",
    "series": "Pokémon",
    "initial_release_year": "2013",
    "gender": "Varies",
    "range_type": "Close-range",
    "image_url": "/Character-images/Greninja.png"
  },
  {
    "name": "Mii Brawler",
    "company": "Nintendo",
    "series": "Mii",
    "initial_release_year": "2006",
    "gender": "Varies",
    "range_type": "Close-range",
    "image_url": "/Character-images/Mii_Brawler.png"
  },
  {
    "name": "Mii Swordfighter",
    "company": "Nintendo",
    "series": "Mii",
    "initial_release_year": "2006",
    "gender": "Varies",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Mii_Swordfighter.png"
  },
  {
    "name": "Mii Gunner",
    "company": "Nintendo",
    "series": "Mii",
    "initial_release_year": "2006",
    "gender": "Varies",
    "range_type": "Long-range",
    "image_url": "/Character-images/Mii_Gunner.png"
  },

  {
    "name": "Palutena",
    "company": "Nintendo",
    "series": "Kid Icarus",
    "initial_release_year": "1986",
    "gender": "Female",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Palutena.png"
  },
  {
    "name": "Pac-Man",
    "company": "Bandai Namco",
    "series": "Pac-Man",
    "initial_release_year": "1980",
    "gender": "Male",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Pac-Man.png"
  },
  {
    "name": "Robin",
    "company": "Nintendo",
    "series": "Fire Emblem",
    "initial_release_year": "2012",
    "gender": "Varies",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Robin.png"
  },
  {
    "name": "Shulk",
    "company": "Nintendo",
    "series": "Xenoblade Chronicles",
    "initial_release_year": "2010",
    "gender": "Male",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Shulk.png"
  },
  {
    "name": "Bowser Jr.",
    "company": "Nintendo",
    "series": "Super Mario",
    "initial_release_year": "2002",
    "gender": "Male",
    "range_type": "Close-range",
    "image_url": "/Character-images/Bowser_Jr..png"
  },
  {
    "name": "Duck Hunt",
    "company": "Nintendo",
    "series": "Duck Hunt",
    "initial_release_year": "1984",
    "gender": "Varies",
    "range_type": "Long-range",
    "image_url": "/Character-images/Duck_Hunt.png"
  },
  {
    "name": "Ryu",
    "company": "Capcom",
    "series": "Street Fighter",
    "initial_release_year": "1987",
    "gender": "Male",
    "range_type": "Close-range",
    "image_url": "/Character-images/Ryu.png"
  },
  {
    "name": "Ken",
    "company": "Capcom",
    "series": "Street Fighter",
    "initial_release_year": "1987",
    "gender": "Male",
    "range_type": "Close-range",
    "image_url": "/Character-images/Ken.png"
  },
  {
    "name": "Cloud",
    "company": "Square Enix",
    "series": "Final Fantasy",
    "initial_release_year": "1997",
    "gender": "Male",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Cloud.png"
  },
  {
    "name": "Corrin",
    "company": "Nintendo",
    "series": "Fire Emblem",
    "initial_release_year": "2015",
    "gender": "Varies",
    "range_type": "Close-range",
    "image_url": "/Character-images/Corrin.png"
  },
  {
    "name": "Bayonetta",
    "company": "PlatinumGames",
    "series": "Bayonetta",
    "initial_release_year": "2009",
    "gender": "Female",
    "range_type": "Close-range",
    "image_url": "/Character-images/Bayonetta.png"
  },
  {
    "name": "Inkling",
    "company": "Nintendo",
    "series": "Splatoon",
    "initial_release_year": "2015",
    "gender": "Varies",
    "range_type": "Close-range",
    "image_url": "/Character-images/Inkling.png"
  },
  {
    "name": "Ridley",
    "company": "Nintendo",
    "series": "Metroid",
    "initial_release_year": "1986",
    "gender": "Male",
    "range_type": "Close-range",
    "image_url": "/Character-images/Ridley.png"
  },
  {
    "name": "Simon Belmont",
    "company": "Konami",
    "series": "Castlevania",
    "initial_release_year": "1986",
    "gender": "Male",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Simon.png"
  },
  {
    "name": "Richter",
    "company": "Konami",
    "series": "Castlevania",
    "initial_release_year": "1993",
    "gender": "Male",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Richter.png"
  },
  {
    "name": "King K. Rool",
    "company": "Nintendo",
    "series": "Donkey Kong",
    "initial_release_year": "1994",
    "gender": "Male",
    "range_type": "Close-range",
    "image_url": "/Character-images/King_k._Rool.png"
  },
  {
    "name": "Isabelle",
    "company": "Nintendo",
    "series": "Animal Crossing",
    "initial_release_year": "2012",
    "gender": "Female",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Isabelle.png"
  },
  {
    "name": "Incineroar",
    "company": "Nintendo",
    "series": "Pok\u00e9mon",
    "initial_release_year": "2016",
    "gender": "Varies",
    "range_type": "Close-range",
    "image_url": "/Character-images/Incineroar.png"
  },
  {
    "name": "Piranha Plant",
    "company": "Nintendo",
    "series": "Super Mario",
    "initial_release_year": "1985",
    "gender": "Varies",
    "range_type": "Close-range",
    "image_url": "/Character-images/Piranha_Plant.png"
  },
  {
    "name": "Joker",
    "company": "Atlus",
    "series": "Persona",
    "initial_release_year": "2016",
    "gender": "Male",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Joker.png"
  },
  {
    "name": "Hero",
    "company": "Square Enix",
    "series": "Dragon Quest",
    "initial_release_year": "1986",
    "gender": "Varies",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Hero.png"
  },
  {
    "name": "Banjo & Kazooie",
    "company": "Microsoft",
    "series": "Banjo-Kazooie",
    "initial_release_year": "1998",
    "gender": "Varies",
    "range_type": "Close-range",
    "image_url": "/Character-images/Banjo_Kazooie.png"
  },
  {
    "name": "Terry Bogard",
    "company": "SNK",
    "series": "Fatal Fury",
    "initial_release_year": "1991",
    "gender": "Male",
    "range_type": "Close-range",
    "image_url": "/Character-images/Terry_Bogard.png"
  },
  {
    "name": "Byleth",
    "company": "Nintendo",
    "series": "Fire Emblem",
    "initial_release_year": "2019",
    "gender": "Varies",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Byleth.png"
  },
  {
    "name": "Min Min",
    "company": "Nintendo",
    "series": "ARMS",
    "initial_release_year": "2017",
    "gender": "Female",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Min_Min.png"
  },
  {
    "name": "Steve",
    "company": "Microsoft",
    "series": "Minecraft",
    "initial_release_year": "2009",
    "gender": "Varies",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Steve.png"
  },
  {
    "name": "Sephiroth",
    "company": "Square Enix",
    "series": "Final Fantasy",
    "initial_release_year": "1997",
    "gender": "Male",
    "range_type": "Mid-range",
    "image_url": "/Character-images/Sephiroth.png"
  },
  {
    "name": "Pyra/Mythra",
    "company": "Nintendo",
    "series": "Xenoblade Chronicles",
    "initial_release_year": "2017",
    "gender": "Female",
    "range_type": "Close-range",
    "image_url": "/Character-images/Pyra_Mythra.png"
  },
  {
    "name": "Kazuya Mishima",
    "company": "Bandai Namco",
    "series": "Tekken",
    "initial_release_year": "1994",
    "gender": "Male",
    "range_type": "Close-range",
    "image_url": "/Character-images/Kazuya_Mishima.png"
  },
  {
    "name": "Sora",
    "company": "Square Enix",
    "series": "Kingdom Hearts",
    "initial_release_year": "2002",
    "gender": "Male",
    "range_type": "Close-range",
    "image_url": "/Character-images/Sora.png"
  }
]